/// Flutter icons Food
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Food
///      fonts:
///       - asset: fonts/Food.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;
import 'package:flutter/widgets.dart';

class Food {
  Food._();

  static const _kFontFam = 'Food';
  static const String? _kFontPkg = null;

  static const IconData food = IconData(0xf0f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snowflake = IconData(0xf2dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
